// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOFgZVd6JebVIJ4ZCFogleRgIUU-zc7mU',
    appId: '1:647910129693:web:ab18fc4d82b7ea175e46f4',
    messagingSenderId: '647910129693',
    projectId: 'half-baked-24565',
    authDomain: 'half-baked-24565.firebaseapp.com',
    storageBucket: 'half-baked-24565.appspot.com',
    measurementId: 'G-E4BXJDMG35',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsfcz8gY9rHHmE4Fbhh0OcD3U-6kFUmao',
    appId: '1:647910129693:android:8af7b7b8044cd3955e46f4',
    messagingSenderId: '647910129693',
    projectId: 'half-baked-24565',
    storageBucket: 'half-baked-24565.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChrA2DUFnCBOF7oKF5uKxAX8tyrX13QfQ',
    appId: '1:647910129693:ios:8243f1b2fab6aac65e46f4',
    messagingSenderId: '647910129693',
    projectId: 'half-baked-24565',
    storageBucket: 'half-baked-24565.appspot.com',
    iosClientId: '647910129693-up2c1pvl9p6clg8755888eiah62fie2n.apps.googleusercontent.com',
    iosBundleId: 'com.example.fb2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChrA2DUFnCBOF7oKF5uKxAX8tyrX13QfQ',
    appId: '1:647910129693:ios:591c3c10c671de7d5e46f4',
    messagingSenderId: '647910129693',
    projectId: 'half-baked-24565',
    storageBucket: 'half-baked-24565.appspot.com',
    iosClientId: '647910129693-m7mgm6s71cp98n7k483rgfr0vf5ggsmk.apps.googleusercontent.com',
    iosBundleId: 'com.example.fb2.RunnerTests',
  );
}
